FROM golang:1.20-alpine

RUN apk --no-cache add curl

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN go mod download && go mod verify
RUN go build -v -o /usr/bin/outclimb cmd/main.go

CMD ["outclimb"]
