FROM node:lts AS build

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN npm ci
RUN npm run build -- --outDir /usr/src/build/

FROM nginx

COPY --from=build /usr/src/app/assets/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*
COPY --from=build /usr/src/build .

CMD ["nginx", "-g", "daemon off;"]
